package com.mmo.tooldemo.greenDao.api;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mmo.tooldemo.greenDao.bean.SucBillInfo;

import com.mmo.tooldemo.greenDao.api.SucBillInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sucBillInfoDaoConfig;

    private final SucBillInfoDao sucBillInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sucBillInfoDaoConfig = daoConfigMap.get(SucBillInfoDao.class).clone();
        sucBillInfoDaoConfig.initIdentityScope(type);

        sucBillInfoDao = new SucBillInfoDao(sucBillInfoDaoConfig, this);

        registerDao(SucBillInfo.class, sucBillInfoDao);
    }
    
    public void clear() {
        sucBillInfoDaoConfig.clearIdentityScope();
    }

    public SucBillInfoDao getSucBillInfoDao() {
        return sucBillInfoDao;
    }

}
